### ISSUE TITLE
Gloss Detail

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/Gallery-of-Glosses#36]
When a user selects a gloss from the collection, they should be able to go to a detail page for a particular Gloss.

We need a matching interface for the following data entry interface
https://glossing-dev.rerum.io/glossing/ng.html#https://devstore.rerum.io/v1/id/614362c3e74876243131a4e0

**Comment by thehabes** [comment]
See #1

**Comment by cubap** [comment]
Note a few things about the form on the linked page:

* **Label for display** (at the bottom) is the Title on the page.
* **Witnesses** link away from this Gloss, but may show an inset/popup.
* **Gloss Text** is edited, but the versions in the linked fragments may be useful to a user.
* **&tltags>** just tells us that the text above needs to be handled differently.
* **language, description, Canonical Reference Locator** show just as they are.
* **target text** will be handled carefully, especially because if there is `text` in the Gloss, this will be a subselection of it.
* **Document, Section, Subsection(s)** are all for sorting and searching only and not shown.
* **notes** is not for the public.
* **tags and themes** should be clickable.

**Comment by leandrumartin** [comment]
What should tags and themes link to when clicked? An idea I have is that the search fields on `/browse/tag` and `/browse/theme` (see the deployment of Pull #44 ) could be modifiable via query parameters, e.g. `/brows/tag?q=virtus`. Clicking the "virtus" tag would therefore link there.

**Comment by leandrumartin** [comment]
What should tags and themes link to when clicked? An idea I have is that the search fields on `/browse/tag` and `/browse/theme` (see the deployment of Pull #44 ) could be modifiable via query parameters, e.g. `/brows/tag?q=virtus`. Clicking the "virtus" tag would therefore link there.
